# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200317_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='mistune转码后的html正文'),
        ),
    ]
